# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: EightBitBoyBlog
email: haertel.dev@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Site description TODO
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.eightbitboy.de" # the base hostname & protocol for your site
twitter_username: EightBitBoy
github_username:  EightBitBoy

# Build settings
markdown: kramdown
